---
title: "Final Project"
author: "Aziz    aaa169@pitt.edu"
date: "October 14, 2016"
output: html_document
---



```{r}

setwd("Users/Abdulaziz/Documents/Master/Data Mining/Project/")

```

```{r}
### Get the data

setwd("./data/")

```


```{r}
library(lubridate)

library(dplyr)


```

```{r}
## Read The data
### stations data
stations <- read.csv("HealthyRideStations2015.csv")

```

```{r}

## 2015 Q3

rentalQ153 <- read.csv("HealthyRideRentals 2015 Q3.csv",na.strings= c("999", "NA", " ", ""))  


### Change the data 

rentalQ153$StartTime <- strptime(rentalQ153$StartTime, format="%m/%d/%Y %H:%M")
rentalQ153$StopTime <- strptime(rentalQ153$StopTime, format="%m/%d/%Y %H:%M")

# rentalQ153$StartTime <- as.POSIXct(rentalQ153$StartTime, format="%m/%d/%Y %H:%M")
# rentalQ153$StopTime <- as.POSIXct(rentalQ153$StopTime, format="%m/%d/%Y %H:%M")



```

```{r}

## 2015 Q4

## Converting from xls to csv

# require(gdata)
# ## install support for xlsx files
# installXLSXsupport()
# excelFile <- ("./HealthyRideRentals 2015 Q4.xlsx")
# ## note that the perl scripts that gdata uses do not cope well will tilde expansion
# ## on *nix machines. So use the full path. 
# numSheets <- sheetCount(excelFile, verbose=TRUE)
# 
# for ( i in 1:numSheets) {
#   mySheet <- read.xls(excelFile, sheet=i)
#   write.csv(mySheet, file=paste(i, "csv", sep="."), row.names=FALSE)
# }

rentalQ154 <- read.csv("HealthyRideRentals 2015 Q4.csv", na.strings= c("999", "NA", " ", ""))  


rentalQ154$StartTime <- strptime(rentalQ154$StartTime, format="%Y-%m-%d %H:%M:%S")
rentalQ154$StopTime <- strptime(rentalQ154$StopTime, format="%Y-%m-%d %H:%M:%S")

# rentalQ154$StartTime <- as.POSIXct(rentalQ154$StartTime)
# rentalQ154$StopTime <- as.POSIXct(rentalQ154$StopTime)


```


```{r}

## 2016 Q1

## Converting from xls to csv

# require(gdata)
# ## install support for xlsx files
# installXLSXsupport()
# excelFile <- ("./HealthyRide Rentals 2016 Q1.xlsx")
# ## note that the perl scripts that gdata uses do not cope well will tilde expansion
# ## on *nix machines. So use the full path.
# 
# 
# mySheet <- read.xls(excelFile)
# write.csv(mySheet, file=paste("HealthyRide Rentals 2016 Q1","csv", sep="."), row.names=FALSE)

rentalQ161 <- read.csv("HealthyRide Rentals 2016 Q1.csv", na.strings= c("999", "NA", " ", ""))  
## Make sure they have the same colunm names 
names(rentalQ161) <- c(names(rentalQ153))

rentalQ161$StartTime <- strptime(rentalQ161$StartTime, format="%Y-%m-%d %H:%M:%S")
rentalQ161$StopTime <- strptime(rentalQ161$StopTime, format="%Y-%m-%d %H:%M:%S")

# rentalQ161$Starttime <- as.POSIXct(rentalQ161$Starttime,format="%Y-%m-%d %H:%M:%S")
# rentalQ161$Stoptime <- as.POSIXct(rentalQ161$Stoptime,format="%Y-%m-%d %H:%M:%S")






```

```{r}

## binding the data together

bike <- rbind(rentalQ153,rentalQ154,rentalQ161)

bike$TripId <- as.factor(bike$TripId)
bike$BikeId <- as.factor(bike$BikeId)
bike$FromStationId <- as.factor(bike$FromStationId)
bike$ToStationId <- as.factor(bike$ToStationId)

```


```{r}

## Splitting the date 



# bike <- bike %>% mutate(
#   year = format(as.POSIXct(StartTime), format = "%Y"),
#   month = format(as.POSIXct(StartTime), format = "%m"),
#   day = format(as.POSIXct(StartTime), format = "%d"),
#   hour = format(as.POSIXct(StartTime), format= "%H")
# )


set_up_features <- function(df) {
  df$StartTime <- strptime(df$StartTime, format="%Y-%m-%d %H:%M:%S")
  df$hour <- as.factor(df$StartTime$hour)
  df$day <-  as.factor(df$StartTime$mday)
  df$wday <- as.factor(df$StartTime$wday)
  df$month <- as.factor(df$StartTime$mon+1) ## starts from 0
  df$year <- as.factor(df$StartTime$year + 1900)
  df
}

bike <- set_up_features(bike)
  
```

```{r}

## Make a summeary for the missing values 

na_data <- sapply(bike, function(x) sum(length(which(is.na(x)))))
na_data


```

```{r}

bike$FromStationName[which(is.na(bike$FromStationId))]


bike$FromStationId[which(is.na(bike$FromStationName))]

## I guss we should just drop them

```



```{r}


bike %>% select(TripId,FromStationId) %>% filter(FromStationId == 1001) 

```

```{r}

### References
# https://github.com/artem-fedosov/bike-sharing-demand/blob/master/read_data.R